# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('bootstrap4', '0005_image_use_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='mediaobject',
            old_name='image',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='button',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, help_text='Optional. Link HTML tag attributes', verbose_name='link tag attributes'),
        ),
        migrations.AlterField(
            model_name='button',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_button', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
