# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_added_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['email'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
